# This file was generated by GoReleaser. DO NOT EDIT.
cask "konduit" do
  version "0.2.5"

  on_macos do
    on_intel do
      url "https://github.com/jace-ys/konduit/releases/download/v#{version}/konduit_#{version}_darwin_amd64.tar.gz"
      sha256 "302664d8df2247cce581fef4c736d03a2676e598b48277d87629a0878035ca3a"
    end
    on_arm do
      url "https://github.com/jace-ys/konduit/releases/download/v#{version}/konduit_#{version}_darwin_arm64.tar.gz"
      sha256 "d0f07f8a947f028c7a0b8bd4d24c347df79119519b1076ce8983f53cb401dcfd"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jace-ys/konduit/releases/download/v#{version}/konduit_#{version}_linux_amd64.tar.gz"
      sha256 "3f4aa1fbd02db4b413f2de2a777e45a69637d2f942bd63dfa14f4ccc2cca9607"
    end
    on_arm do
      url "https://github.com/jace-ys/konduit/releases/download/v#{version}/konduit_#{version}_linux_arm64.tar.gz"
      sha256 "3abafc6fb91685ad01e8d623be144b1e1a1e2e6ab884a20394266707af9066f9"
    end
  end

  name "konduit"
  desc "Helm meets Kustomize, but without the YAML"
  homepage "https://github.com/jace-ys/konduit"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "helm@3",
      "kustomize",
    ]

  binary "konduit"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/konduit"]
  end

  # No zap stanza required

  caveats <<~EOS
    Konduit currently only works with Helm 3. Since helm@3 is keg-only, you need to add it to your PATH or use the --helm-command flag.
  EOS
end
