# This file was generated by GoReleaser. DO NOT EDIT.
cask "konduit" do
  version "0.2.6"

  on_macos do
    on_intel do
      sha256 "d5e1b7f049f5e33847cfbb44ce8dd98a1b32530f2e8acc1dacaef22774498eb0"
      url "https://github.com/jace-ys/konduit/releases/download/v#{version}/konduit_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "57034859c9bc5e83d79d1b42348b3fd2b8ef821f58e516d9f3d51e5f9284b3b9"
      url "https://github.com/jace-ys/konduit/releases/download/v#{version}/konduit_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d6a1f4836dd54e5dc32b39210250cdce7e23b5a98898108569e4e4f407d04782"
      url "https://github.com/jace-ys/konduit/releases/download/v#{version}/konduit_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "82155f3a8f515dfcfa3a48bdbec837ffe41af95c739eee65da5f0735a98e04d5"
      url "https://github.com/jace-ys/konduit/releases/download/v#{version}/konduit_#{version}_linux_arm64.tar.gz"
    end
  end

  name "konduit"
  desc "Helm meets Kustomize, but without the YAML"
  homepage "https://github.com/jace-ys/konduit"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "helm@3",
      "kustomize",
    ]

  binary "konduit"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/konduit"]
  end

  # No zap stanza required

  caveats <<~EOS
    Konduit currently only works with Helm 3. Since helm@3 is keg-only, you need to add it to your PATH or use the --helm-command flag.
  EOS
end
