# This file was generated by GoReleaser. DO NOT EDIT.
cask "konduit" do
  name "konduit"
  desc "Helm meets Kustomize, but without the YAML"
  homepage "https://github.com/jace-ys/konduit"
  version "0.2.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "konduit"
  depends_on formula: [
      "helm@3",
      "kustomize",
    ]

  on_macos do
    on_intel do
      url "https://github.com/jace-ys/konduit/releases/download/v#{version}/konduit_#{version}_darwin_amd64.tar.gz"
      sha256 "6c1b030677d6839c5a5a199b60d23a539cdbc7b57d4730d480f09ce70b3a5464"
    end
    on_arm do
      url "https://github.com/jace-ys/konduit/releases/download/v#{version}/konduit_#{version}_darwin_arm64.tar.gz"
      sha256 "94c55d0719378d0a33944d8a828a8af38a50dce607e9aabe8e52d69e91daacad"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jace-ys/konduit/releases/download/v#{version}/konduit_#{version}_linux_amd64.tar.gz"
      sha256 "5716cf0001ffc694d35a44f850341052389342341a8c5d451775fa0976e290d8"
    end
    on_arm do
      url "https://github.com/jace-ys/konduit/releases/download/v#{version}/konduit_#{version}_linux_arm64.tar.gz"
      sha256 "c3a2c5e56f19a08d115925ea5884fdb601f1a1121dbbf6fcbb49c0e902d3cc0e"
    end
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/konduit"]
  end

  caveats do
    "Konduit currently only works with Helm 3. Since helm@3 is keg-only, you need to add it to your PATH or use the --helm-command flag."
  end

  # No zap stanza required
end
